### PR TITLE
Feature/side filter

### PR DESCRIPTION
**Pull request by clmntd**
- added side filter and toggle with functional states

### CODE REVIEW

**Comment by RAYMUNDOOOO** [comment]
@clmntd There's a few conflicts. Do you think you can resolve them first and then submit another request?

**Comment by clmntd** [comment]
@RAYMUNDOOOO merge conflicts are fixed. Is "The Oracle" supposed to be 2 lines on the navbar?

**Comment by RAYMUNDOOOO** [comment]
> @RAYMUNDOOOO merge conflicts are fixed. Is "The Oracle" supposed to be 2 lines on the navbar?

It shouldn't be. I don't recall it being 2 lines on my laptop but we can fix that later I reckon.

**Review by RAYMUNDOOOO — APPROVED** [review]
Looks really good. Doubt i would've been able to do this myself hahaha.

**Pull request merged**
